paths:
  raw_data: data/raw
  bronze: data/bronze
  silver: data/silver
  gold: data/gold

  history_db: ~/.config/google-chrome/Default/History

  ram_logs: data/raw/ram

  history_logs: data/raw/history

  models: models

  reports: reports